-- ============================================
-- TAREA 4: Script de Importación de Base de Datos
-- Ejemplo de base de datos Biblioteca
-- ============================================

-- Crear base de datos
CREATE DATABASE biblioteca;

-- Conectar a la base de datos
\c biblioteca

-- ============================================
-- CREAR TABLAS
-- ============================================

-- Tabla de Alumnos
CREATE TABLE alumnos (
    matricula INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    grado VARCHAR(20) NOT NULL,
    email VARCHAR(100) UNIQUE,
    fecha_inscripcion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de Libros
CREATE TABLE libros (
    id_libro INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(100) NOT NULL,
    autor VARCHAR(100) NOT NULL,
    anio_publicacion INTEGER NOT NULL,
    isbn VARCHAR(13) UNIQUE,
    cantidad_disponible INTEGER DEFAULT 1
);

-- Tabla de Categorías
CREATE TABLE categorias (
    id_categoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    descripcion TEXT
);

-- Tabla de relación entre Libros y Categorías
CREATE TABLE libro_categoria (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_libro INTEGER NOT NULL,
    id_categoria INTEGER NOT NULL,
    FOREIGN KEY (id_libro) REFERENCES libros(id_libro) ON DELETE CASCADE,
    FOREIGN KEY (id_categoria) REFERENCES categorias(id_categoria) ON DELETE CASCADE,
    UNIQUE(id_libro, id_categoria)
);

-- Tabla de Préstamos
CREATE TABLE prestamos (
    id_prestamo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricula INTEGER NOT NULL,
    id_libro INTEGER NOT NULL,
    fecha_prestamo DATE NOT NULL,
    fecha_devolucion DATE,
    estado VARCHAR(20) DEFAULT 'activo',
    FOREIGN KEY (matricula) REFERENCES alumnos(matricula) ON DELETE CASCADE,
    FOREIGN KEY (id_libro) REFERENCES libros(id_libro) ON DELETE CASCADE
);

-- ============================================
-- CREAR ÍNDICES
-- ============================================

CREATE INDEX idx_alumnos_email ON alumnos(email);
CREATE INDEX idx_alumnos_grado ON alumnos(grado);
CREATE INDEX idx_libros_autor ON libros(autor);
CREATE INDEX idx_libros_isbn ON libros(isbn);
CREATE INDEX idx_prestamos_alumno ON prestamos(matricula);
CREATE INDEX idx_prestamos_libro ON prestamos(id_libro);
CREATE INDEX idx_prestamos_estado ON prestamos(estado);

-- ============================================
-- INSERTAR DATOS DE PRUEBA
-- ============================================

-- Insertar categorías
INSERT INTO categorias (nombre, descripcion) VALUES
('Programación', 'Libros sobre lenguajes de programación y desarrollo de software'),
('Bases de Datos', 'Libros sobre diseño y administración de bases de datos'),
('Redes', 'Libros sobre redes y seguridad informática'),
('Algoritmos', 'Libros sobre algoritmos y estructuras de datos'),
('Web', 'Libros sobre desarrollo web y tecnologías web');

-- Insertar alumnos
INSERT INTO alumnos (nombre, grado, email) VALUES
('Juan Pérez García', '1ro', 'juan.perez@escuela.edu'),
('María López Rodríguez', '2do', 'maria.lopez@escuela.edu'),
('Carlos Rodríguez López', '1ro', 'carlos.rodriguez@escuela.edu'),
('Ana Martínez González', '3ro', 'ana.martinez@escuela.edu'),
('Pedro Sánchez Martín', '2do', 'pedro.sanchez@escuela.edu');

-- Insertar libros
INSERT INTO libros (titulo, autor, anio_publicacion, isbn, cantidad_disponible) VALUES
('Clean Code', 'Robert C. Martin', 2008, '9780132350884', 3),
('The Pragmatic Programmer', 'Andrew Hunt', 1999, '9780135957059', 2),
('Database Design Manual', 'Tapio Lahdenmaki', 2009, '9780596155896', 1),
('Introduction to Algorithms', 'Thomas H. Cormen', 2009, '9780262033848', 4),
('Web Design for Developers', 'Brian P. Hogan', 2009, '9781934356135', 2),
('PostgreSQL 12 Complete', 'Julien Rouhaud', 2020, '9781838988609', 2),
('Python for Data Analysis', 'Wes McKinney', 2012, '9781491957660', 3);

-- Relacionar libros con categorías
INSERT INTO libro_categoria (id_libro, id_categoria) VALUES
(1, 1), (1, 4),      -- Clean Code: Programación y Algoritmos
(2, 1),              -- The Pragmatic Programmer: Programación
(3, 2),              -- Database Design Manual: Bases de Datos
(4, 4),              -- Introduction to Algorithms: Algoritmos
(5, 5),              -- Web Design for Developers: Web
(6, 2),              -- PostgreSQL 12 Complete: Bases de Datos
(7, 1);              -- Python for Data Analysis: Programación

-- Insertar préstamos
INSERT INTO prestamos (matricula, id_libro, fecha_prestamo, fecha_devolucion, estado) VALUES
(1, 1, '2026-01-15', '2026-01-29', 'devuelto'),
(2, 3, '2026-01-20', NULL, 'activo'),
(1, 4, '2026-01-25', NULL, 'activo'),
(3, 2, '2026-01-26', NULL, 'activo'),
(4, 5, '2026-01-28', NULL, 'activo'),
(5, 6, '2026-01-29', NULL, 'activo');

-- ============================================
-- CONSULTAS DE VALIDACIÓN
-- ============================================

-- Contar registros en cada tabla
SELECT 'alumnos' as tabla, COUNT(*) as registros FROM alumnos
UNION ALL
SELECT 'libros', COUNT(*) FROM libros
UNION ALL
SELECT 'categorias', COUNT(*) FROM categorias
UNION ALL
SELECT 'prestamos', COUNT(*) FROM prestamos;

-- Libros con sus categorías
SELECT l.titulo, l.autor, string_agg(c.nombre, ', ') as categorias
FROM libros l
LEFT JOIN libro_categoria lc ON l.id_libro = lc.id_libro
LEFT JOIN categorias c ON lc.id_categoria = c.id_categoria
GROUP BY l.id_libro, l.titulo, l.autor
ORDER BY l.titulo;

-- Préstamos activos
SELECT a.nombre, l.titulo, p.fecha_prestamo
FROM prestamos p
JOIN alumnos a ON p.matricula = a.matricula
JOIN libros l ON p.id_libro = l.id_libro
WHERE p.estado = 'activo'
ORDER BY p.fecha_prestamo DESC;

-- Alumnos con más préstamos
SELECT a.nombre, COUNT(p.id_prestamo) as total_prestamos
FROM alumnos a
LEFT JOIN prestamos p ON a.matricula = p.matricula
GROUP BY a.matricula, a.nombre
ORDER BY total_prestamos DESC;

-- Libro más solicitado
SELECT l.titulo, COUNT(p.id_prestamo) as veces_prestado
FROM libros l
LEFT JOIN prestamos p ON l.id_libro = p.id_libro
GROUP BY l.id_libro, l.titulo
ORDER BY veces_prestado DESC
LIMIT 5;
